# Generated by Django 6.0.2 on 2026-03-16 15:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="product",
        ),
        migrations.AddField(
            model_name="subscription",
            name="category",
            field=models.CharField(default="Milk", max_length=100),
        ),
        migrations.AddField(
            model_name="subscription",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="subscription",
            name="customer_name",
            field=models.CharField(default="Anonymous", max_length=200),
        ),
        migrations.AddField(
            model_name="subscription",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="plan_name",
            field=models.CharField(default="Daily Fresh", max_length=100),
        ),
        migrations.AddField(
            model_name="subscription",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
