# Generated by Django 6.0.2 on 2026-03-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "subscription",
            "0002_remove_subscription_product_subscription_category_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="product_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="plan_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
