# Generated by Django 6.0.2 on 2026-03-16 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_product_category_product_created_at_product_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
