# Generated by Django 6.0.2 on 2026-03-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_product_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price_data",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
