name: Deploy Milkman Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Azure VM via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo "Connected to VM"

            cd ~/Bm-Milkman-Project-Final || exit

            echo "Pull latest code"
            git pull origin main

            echo "Backend setup"
            cd backend
            source venv/bin/activate
            pip install -r requirements.txt
            python manage.py migrate
            sudo systemctl restart milkman

            echo "Frontend build"
            cd ../frontend
            npm install
            npm run build
            sudo rm -rf /var/www/dairymart/*
            sudo cp -r dist/* /var/www/dairymart/

            echo "Restart Nginx"
            sudo systemctl restart nginx

            echo "Deployment done"
